Task_2_2_1
K4rsion/JAVA pull request #27
Opened 2023-05-02 07:50 UTC by K4rsion

2023-06-16 12:24 UTC, shadrina requested changes

2023-06-16 12:24 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kgurin/Baker.java
> +                Order order = Main.takeFromQueue();
Вот это выглядит хрупко и небезопасно. У тебя `Main.queue` открыта для всего пакета, "бери, кто хочет". И надо везде следить, что доступ осуществляется только через synchronized. А зачем, если можно ограничить доступ к `Main.queue` только через методы Main? Это первый момент. Второй: почему логику строк 52-56 не заключить в тот же `Main.takeFromQueue()`?

2023-06-16 12:24 UTC, shadrina commented on Task_2_2_1/src/main/java/ru/nsu/kgurin/Deliverer.java
> +                List<Order> orders = Main.takeFromStock(capacity);
То же самое

2023-06-19 11:54 UTC, shadrina commented
Я все еще жду, что ты сегодня забукаешь слот на встречу.

2023-06-19 11:57 UTC, shadrina commented
А, вижу, что ты просто неправильно выставил время. Остался слот 8:30-9:00. Забукай правильно пожалкйста.

2023-06-19 13:07 UTC, gurinkirill commented
Привет! Сейчас вроде нормально. С 20:45 выставил

2023-06-19 14:10 UTC, merged